language: none

branches:
  only:
  - cmake_support

before_install:
  - sudo apt-get install ninja-build texlive

script:
  - mkdir build
  - cd build
  - export TEXINPUTS=$(pwd)/include;$(pwd)/include/img
  - cmake -G Ninja ..
  - ninja
