language: none

branches:
  only:
  - cmake_support

before_install:
  - sudo apt-get install -y -qq ninja-build
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
<<<<<<< HEAD
  - echo "deb http://miktex.org/download/ubuntu xenial universe" | sudo tee /etc/apt/sources.list.d/miktex.list
>>>>>>> 7735377b8dacb576be818baec893ab85682b583f
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq miktex

script:
  - ls
