language: none

branches:
  only:
  - cmake_support

before_install:
    # installing the tools
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq cmake ninja-build wget xzdec

    # installing latest TexLive (basic schema)
    - chmod +x ./.travis/install-texlive-latest.sh
    - ./.travis/install-texlive-latest.sh
    - sudo apt-get install -y -qq texlive-lang-european

script:
  - source ./.travis/export_variables.sh
  - which pdflatex
  - which tlmgr

  - tlmgr init-usertree
  - tlmgr install $(cat latex_packages.txt)
  
  # initialize hyphens
  # - mktexlsr
  # - updmap-sys
  # - fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --byhyphen "language.dat"
  # - fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --byhyphen "language.def"
  # - fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --byhyphen "language.dat.lua"

  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - ninja
