language: none

branches:
  only:
  - cmake_support

before_install:
  - sudo apt-get install -y -qq ninja-build xsltproc
  - git clone https://github.com/MiKTeX/miktex.git
  - cd miktex
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install

script:
  - ls
