- os: linux
  compiler: gcc
  addons:
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
      packages: [ 'g++-4.8', 'libstdc++-4.8-dev', 'ninja-build', 'cmake' ]
  env: CMAKE_BUILD_TYPE=RELEASE

# Build steps
script:
  - mkdir build
  - cd build
  - ${DEPS_DIR}/cmake/bin/cmake -G Ninja .. && ninja
